# -------------------- Self Manage
camunda:
  client:
    mode: selfManaged
    zeebe:
      enabled: true
      grpc-address: http://localhost:26500
      rest-address: http://localhost:8088
      preferRestOverGrpc: false
    tasklist:
      rest-address: http://localhost:8082
      user-name: demo
      user-password: demo

server:
  port: 8585
