# -------------------- Self Manage
camunda:
  client:
    mode: selfManaged
    zeebe:
      enabled: true
      grpc-address: http://localhost:26500
      rest-address: http://localhost:8088
      preferRestOverGrpc: false
server:
  port: 8585
